### ISSUE TITLE
Erro ao tentar submeter o teste

### ISSUE THREAD

**Issue by Brunospo** [Impact-Plataform/Processo-Seletivo#1]
Olá, bom dia!! Fui tentar enviar os dados e me deparei com o seguinte erro:
![image](https://user-images.githubusercontent.com/38073417/225316463-d180704c-f8c1-4f66-a530-8d970a8161d8.png)

**Comment by RafaelFino** [comment]
Olá Bruno, obrigado por reportar, a URL informada na documentação estava errada, fizemos a correção! se vc puder por gentileza tentar novamente.

**Comment by RafaelFino** [comment]
E por favor, dê uma olhada nas URLs corretas: https://github.com/Impact-Plataform/Processo-Seletivo/blob/master/README.md


Linha | Descrição | Valor no arquivo | Novo valor
-- | -- | -- | --
29 | Caminho para buscar a chave de criptografia | Key_url = '## URL PARA BAIXAR A CHAVE DE CRIPTOGRAFIA ##' | key_url = 'http://ingress-impact-platform.duckdns.org/key'
54 | Precisamos do seu nome | name = 'SEU NOME' | name = "fulano"
55 | Precisamos do seu e-mail | email = 'SEU EMAIL' | email = "fulano@email.com"
56 | Precisamos do seu telefone | phone = 'SEU TELEFONE COM DDD' | phone = "(21) 98888-7777"
67 | Caminho para que esse programa consiga nos enviar os resultados e seus dados | post_url = '## URL PARA ENVIAR O TESTE ##' | post_url = 'http://ingress-impact-platform.duckdns.org/apply'

**Comment by Impact-Plataform** [comment]
Boa tarde, Bruno. Tudo bem?

Pode tentar novamente, por favor?

https://github.com/Impact-Plataform/Processo-Seletivo

Obrigado

**Comment by Brunospo** [comment]
Olá, boa tarde!

Depois que o Rafael fez a correção, eu tentei novamente e deu certo. Devo tentar novamente?

**Comment by Impact-Plataform** [comment]
Bom dia, Bruno.
Tudo bem?
Já recebemos o seu teste.
Fique atento ao seu email.

Abraço,
Equipe Plataforma Impact
