### ISSUE TITLE
Problema no processo seletivo

### ISSUE THREAD

**Issue by Raph2ll** [Impact-Plataform/Processo-Seletivo#2]
Não estou conseguindo terminar o Processo Seletivo. 
![image](https://user-images.githubusercontent.com/66336767/225732955-785a331a-b4b2-4460-a968-a4ceabd78a90.png)

**Comment by RafaelFino** [comment]
Olá, por favor, dê uma olhada na documentação, a URL da linha 29 está errada



Linha | Descrição | Valor no arquivo | Novo valor
-- | -- | -- | --
29 | Caminho para buscar a chave de criptografia | Key_url = '## URL PARA BAIXAR A CHAVE DE CRIPTOGRAFIA ##' | key_url = 'http://ingress-impact-platform.duckdns.org/key'
54 | Precisamos do seu nome | name = 'SEU NOME' | name = "fulano"
55 | Precisamos do seu e-mail | email = 'SEU EMAIL' | email = "fulano@email.com"
56 | Precisamos do seu telefone | phone = 'SEU TELEFONE COM DDD' | phone = "(21) 98888-7777"
67 | Caminho para que esse programa consiga nos enviar os resultados e seus dados | post_url = '## URL PARA ENVIAR O TESTE ##' | post_url = 'http://ingress-impact-platform.duckdns.org/apply'

Deveria ser **http://ingress-impact-platform.duckdns.org/key** e está **impact-server.com**, por favor verifique esses parametros, haviam alguns problemas em uma versão anterior.

Fizemos as correções nessa documentação recentemente, verifique esses valores e tente novamente por ravor.

**Comment by Raph2ll** [comment]
Consegui resolver obrigado @RafaelFino !!!
![image](https://user-images.githubusercontent.com/66336767/225778825-6cee5b1c-14f1-4266-8815-c1827e067f46.png)
